-- =====================================================================
-- ShelfLife :: schema.sql
-- The complete database schema PLUS demo seed data, in one idempotent script.
--
-- HOW THIS RUNS: Spring Boot's SQL init (spring.sql.init.mode=always,
-- spring.sql.init.schema-locations=classpath:db/schema.sql) executes this file
-- against PostgreSQL on EVERY application startup, before Hibernate validates
-- the mapping. Because it runs on every boot (not once), every statement here is
-- written to be safely re-runnable:
--   * CREATE TABLE / CREATE INDEX use IF NOT EXISTS.
--   * Seed INSERTs use ON CONFLICT DO NOTHING, keyed on the natural unique
--     columns (roles.name, users.email, warehouses.warehouse_code, products.sku,
--     and the (warehouse_id, sku) uniqueness of a shelf row).
-- A `docker compose down -v && up` therefore re-creates and re-seeds cleanly with
-- no "relation already exists" or duplicate-key/constraint violations.
--
-- Conventions:
--   * Status fields are VARCHAR + CHECK (not native PG enums) so they map cleanly
--     to JPA @Enumerated(EnumType.STRING). There are no native enum types.
--   * Surrogate keys are BIGINT GENERATED BY DEFAULT AS IDENTITY; products use the
--     natural key `sku` (VARCHAR). All timestamps are TIMESTAMPTZ DEFAULT now().
-- =====================================================================

-- ---------------------------------------------------------------------
-- roles
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS roles (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

-- ---------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(150) NOT NULL,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role_id       BIGINT NOT NULL,
    status        VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
                      CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED')),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE INDEX IF NOT EXISTS idx_users_role_id ON users (role_id);

-- ---------------------------------------------------------------------
-- refresh_tokens
-- Refresh-token store for JWT auth: server-side revocation (logout) + rotation.
-- Only the SHA-256 hash (hex, 64 chars) of the opaque refresh token is persisted.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    token_hash VARCHAR(64)  NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ  NOT NULL,
    revoked    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id ON refresh_tokens (user_id);

-- ---------------------------------------------------------------------
-- warehouses
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS warehouses (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_code VARCHAR(50)  NOT NULL UNIQUE,
    warehouse_name VARCHAR(150) NOT NULL,
    address        VARCHAR(500)
);

-- ---------------------------------------------------------------------
-- picker_warehouse_mapping (composite PK)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS picker_warehouse_mapping (
    picker_id    BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL,
    CONSTRAINT pk_picker_warehouse PRIMARY KEY (picker_id, warehouse_id),
    CONSTRAINT fk_pwm_picker    FOREIGN KEY (picker_id)    REFERENCES users (id),
    CONSTRAINT fk_pwm_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id)
);

CREATE INDEX IF NOT EXISTS idx_pwm_warehouse_id ON picker_warehouse_mapping (warehouse_id);

-- ---------------------------------------------------------------------
-- picker_active_warehouse
-- The picker's active warehouse for the (stateless JWT) session.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS picker_active_warehouse (
    picker_id    BIGINT PRIMARY KEY,
    warehouse_id BIGINT      NOT NULL,
    selected_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_paw_picker    FOREIGN KEY (picker_id)    REFERENCES users (id),
    CONSTRAINT fk_paw_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id)
);

-- ---------------------------------------------------------------------
-- products (sku is the natural primary key)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS products (
    sku     VARCHAR(64) PRIMARY KEY,
    name    VARCHAR(255) NOT NULL,
    barcode VARCHAR(128),
    unit    VARCHAR(32)
);

CREATE INDEX IF NOT EXISTS idx_products_barcode ON products (barcode);

-- ---------------------------------------------------------------------
-- shelf_locations
-- location_code format example: 'Aisle_A-Bay_04-Shelf_2'; one row per (warehouse, sku).
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS shelf_locations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id  BIGINT NOT NULL,
    sku           VARCHAR(64) NOT NULL,
    aisle         VARCHAR(32),
    bay           VARCHAR(32),
    shelf         VARCHAR(32),
    location_code VARCHAR(64) NOT NULL,
    CONSTRAINT fk_shelf_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id),
    CONSTRAINT fk_shelf_sku       FOREIGN KEY (sku)          REFERENCES products (sku),
    CONSTRAINT uq_shelf_warehouse_sku UNIQUE (warehouse_id, sku)
);

CREATE INDEX IF NOT EXISTS idx_shelf_sku ON shelf_locations (sku);

-- ---------------------------------------------------------------------
-- orders
-- customer_id is VARCHAR(64) to store string ids.
-- picker_id is set when a picker claims the order.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS orders (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(64) NOT NULL UNIQUE,
    customer_id  VARCHAR(64),
    warehouse_id BIGINT NOT NULL,
    picker_id    BIGINT,
    status       VARCHAR(20) NOT NULL DEFAULT 'PENDING'
                     CHECK (status IN ('PENDING', 'ASSIGNED', 'PICKING', 'COMPLETED', 'DISPATCHED')),
    version      INTEGER NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_orders_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id),
    CONSTRAINT fk_orders_picker    FOREIGN KEY (picker_id)    REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_orders_warehouse_id ON orders (warehouse_id);
CREATE INDEX IF NOT EXISTS idx_orders_status       ON orders (status);
CREATE INDEX IF NOT EXISTS idx_orders_picker_id    ON orders (picker_id);

-- ---------------------------------------------------------------------
-- order_items
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS order_items (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         BIGINT NOT NULL,
    sku              VARCHAR(64) NOT NULL,
    item_name        VARCHAR(255) NOT NULL,
    ordered_quantity INTEGER NOT NULL,
    picked_quantity  INTEGER NOT NULL DEFAULT 0,
    status           VARCHAR(20) NOT NULL DEFAULT 'PENDING'
                         CHECK (status IN ('PENDING', 'PICKED', 'SKIPPED')),
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_order_items_sku   FOREIGN KEY (sku)      REFERENCES products (sku)
);

CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items (order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_sku      ON order_items (sku);

-- ---------------------------------------------------------------------
-- pick_sessions
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pick_sessions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT NOT NULL,
    picker_id  BIGINT NOT NULL,
    start_time TIMESTAMPTZ,
    end_time   TIMESTAMPTZ,
    status     VARCHAR(20) NOT NULL DEFAULT 'OPEN'
                   CHECK (status IN ('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT fk_pick_sessions_order  FOREIGN KEY (order_id)  REFERENCES orders (id),
    CONSTRAINT fk_pick_sessions_picker FOREIGN KEY (picker_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_pick_sessions_order_id  ON pick_sessions (order_id);
CREATE INDEX IF NOT EXISTS idx_pick_sessions_picker_id ON pick_sessions (picker_id);

-- ---------------------------------------------------------------------
-- pick_logs
-- sku/location are denormalized scan snapshots (no FK by design — immutable history).
-- scan_id is an optional idempotency key; the UNIQUE index treats NULLs as distinct.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pick_logs (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    sku        VARCHAR(64) NOT NULL,
    quantity   INTEGER NOT NULL,
    location   VARCHAR(64),
    scan_time  TIMESTAMPTZ NOT NULL DEFAULT now(),
    scan_id    VARCHAR(64),
    CONSTRAINT fk_pick_logs_session FOREIGN KEY (session_id) REFERENCES pick_sessions (id)
);

CREATE INDEX IF NOT EXISTS idx_pick_logs_session_id ON pick_logs (session_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_pick_logs_scan_id ON pick_logs (scan_id);

-- ---------------------------------------------------------------------
-- audit_logs
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_logs (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   BIGINT NOT NULL,
    action    VARCHAR(100) NOT NULL,
    order_id  BIGINT,
    sku       VARCHAR(64),
    location  VARCHAR(64),
    timestamp TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_audit_user_id  ON audit_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_audit_order_id ON audit_logs (order_id);

-- =====================================================================
-- SEED DATA (idempotent — ON CONFLICT DO NOTHING on natural unique columns)
-- =====================================================================

-- Roles -----------------------------------------------------------------
INSERT INTO roles (name) VALUES ('CENTRAL_ADMIN'), ('HUB_PICKER')
    ON CONFLICT (name) DO NOTHING;

-- Demo users ------------------------------------------------------------
-- BCrypt hashes generated for the documented demo passwords:
--   admin@shelflife.com  -> Admin@123
--   picker@shelflife.com -> Picker@123
-- role_id is resolved by the natural key (roles.name) so it is independent of
-- whatever IDENTITY value the role row happened to receive.
INSERT INTO users (name, email, password_hash, role_id, status)
SELECT 'Central Admin', 'admin@shelflife.com',
       '$2a$10$XuRRVRlbmFjb.pkZvf2SP.whxeh9nv6W0yNyRK3AksYzmdG0drrFa',
       r.id, 'ACTIVE'
FROM roles r WHERE r.name = 'CENTRAL_ADMIN'
    ON CONFLICT (email) DO NOTHING;

INSERT INTO users (name, email, password_hash, role_id, status)
SELECT 'Hub Picker', 'picker@shelflife.com',
       '$2a$10$CYlRG.Mv/bXkid2Yd6OudOYLajG1WjUExqyYdiDx/w3zA3Bga0TTu',
       r.id, 'ACTIVE'
FROM roles r WHERE r.name = 'HUB_PICKER'
    ON CONFLICT (email) DO NOTHING;

-- Warehouses ------------------------------------------------------------
INSERT INTO warehouses (warehouse_code, warehouse_name, address) VALUES
    ('WH-MAIN',  'Main Distribution Center', '100 Central Ave, Metro City'),
    ('WH-NORTH', 'North Regional Hub',       '42 North Loop, Riverdale')
    ON CONFLICT (warehouse_code) DO NOTHING;

-- Map the demo picker to both warehouses so warehouse selection is demoable.
-- Resolved by natural keys (email / warehouse_code); composite PK guards re-runs.
INSERT INTO picker_warehouse_mapping (picker_id, warehouse_id)
SELECT u.id, w.id
FROM users u, warehouses w
WHERE u.email = 'picker@shelflife.com'
  AND w.warehouse_code IN ('WH-MAIN', 'WH-NORTH')
    ON CONFLICT ON CONSTRAINT pk_picker_warehouse DO NOTHING;

-- Products --------------------------------------------------------------
INSERT INTO products (sku, name, barcode, unit) VALUES
    ('SKU-1001', 'Wireless Mouse',          '0102030401001', 'EA'),
    ('SKU-1002', 'USB-C Charging Cable',    '0102030401002', 'EA'),
    ('SKU-1003', 'Mechanical Keyboard',     '0102030401003', 'EA'),
    ('SKU-1004', 'Laptop Stand',            '0102030401004', 'EA'),
    ('SKU-1005', '27-inch Monitor',         '0102030401005', 'EA')
    ON CONFLICT (sku) DO NOTHING;

-- Shelf locations (master location mapping, BRD 3.2) --------------------
-- One row per (warehouse, sku); ON CONFLICT keyed on that uniqueness constraint.
-- Codes are seeded in route (location_code) order for a tidy picking demo.
INSERT INTO shelf_locations (warehouse_id, sku, aisle, bay, shelf, location_code)
SELECT w.id, v.sku, v.aisle, v.bay, v.shelf, v.location_code
FROM warehouses w
JOIN (VALUES
        ('SKU-1001', 'A', '01', '1', 'Aisle_A-Bay_01-Shelf_1'),
        ('SKU-1002', 'A', '02', '1', 'Aisle_A-Bay_02-Shelf_1'),
        ('SKU-1003', 'B', '01', '2', 'Aisle_B-Bay_01-Shelf_2'),
        ('SKU-1004', 'B', '03', '1', 'Aisle_B-Bay_03-Shelf_1'),
        ('SKU-1005', 'C', '02', '3', 'Aisle_C-Bay_02-Shelf_3')
     ) AS v(sku, aisle, bay, shelf, location_code) ON TRUE
WHERE w.warehouse_code = 'WH-MAIN'
    ON CONFLICT ON CONSTRAINT uq_shelf_warehouse_sku DO NOTHING;


-- Seed shelf locations mapping each product SKU to a physical location in WH-MAIN
INSERT INTO shelf_locations (warehouse_id, sku, aisle, bay, shelf, location_code)
SELECT w.id, 'SKU-1001', 'A', '01', '1', 'Aisle_A-Bay_01-Shelf_1'
FROM warehouses w WHERE w.warehouse_code = 'WH-MAIN'
ON CONFLICT (warehouse_id, sku) DO NOTHING;

INSERT INTO shelf_locations (warehouse_id, sku, aisle, bay, shelf, location_code)
SELECT w.id, 'SKU-1002', 'A', '01', '2', 'Aisle_A-Bay_01-Shelf_2'
FROM warehouses w WHERE w.warehouse_code = 'WH-MAIN'
ON CONFLICT (warehouse_id, sku) DO NOTHING;

INSERT INTO shelf_locations (warehouse_id, sku, aisle, bay, shelf, location_code)
SELECT w.id, 'SKU-1003', 'A', '02', '1', 'Aisle_A-Bay_02-Shelf_1'
FROM warehouses w WHERE w.warehouse_code = 'WH-MAIN'
ON CONFLICT (warehouse_id, sku) DO NOTHING;

INSERT INTO shelf_locations (warehouse_id, sku, aisle, bay, shelf, location_code)
SELECT w.id, 'SKU-1004', 'B', '01', '1', 'Aisle_B-Bay_01-Shelf_1'
FROM warehouses w WHERE w.warehouse_code = 'WH-MAIN'
ON CONFLICT (warehouse_id, sku) DO NOTHING;

INSERT INTO shelf_locations (warehouse_id, sku, aisle, bay, shelf, location_code)
SELECT w.id, 'SKU-1005', 'B', '02', '1', 'Aisle_B-Bay_02-Shelf_1'
FROM warehouses w WHERE w.warehouse_code = 'WH-MAIN'
ON CONFLICT (warehouse_id, sku) DO NOTHING;